### ISSUE TITLE
Invalid object path when specifying group and channels

### ISSUE THREAD

**Issue by shihabkhan1** [adamreeve/npTDMS#110]
Hi

I have a TDMS file created using cRIO by NI. When I use the following code:

```
from nptdms import TdmsFile

tdms_file = TdmsFile("SN3595straingauges103-13-1908-39-49-AM.tdms")
```

I get the following warning--

> WARNING:nptdms.tdms:Last segment of file has unknown size, not attempting to read it

When I try to get the channel data using,
`channel = tdms_file.object("_unnamedTask<0>","Strain_0")`

I get the following error --

>   File "C:\Users\mkha0010\AppData\Local\Continuum\anaconda3\lib\site-packages\nptdms\tdms.py", line 157, in object
>     raise KeyError("Invalid object path: %s" % object_path)
> 
> KeyError: 'Invalid object path: /'

Can you please tell me what's wrong? I've attached the file here as well. The TDMS file and my python script are kept in the same directory.

[SN3595straingauges103-13-1908-39-49-AM.zip](https://github.com/adamreeve/npTDMS/files/2965177/SN3595straingauges103-13-1908-39-49-AM.zip)

**Comment by adamreeve** [comment]
Hi, sorry for the delay in replying to this. The problem is that the segment size had all bytes set to `0xFF`. The NI documentation says this should only happen when there was a crash. The file only had one segment header, so npTDMS didn't attempt to read any of the data at all. I've now made a change to try to read until the end of the file. It looks like the data wasn't all written so some is missing, but most of the data should still be read now.
