### ISSUE TITLE
Serial reading and streaming of incoming segments

### ISSUE THREAD

**Issue by ArzelaAscoIi** [adamreeve/npTDMS#145]
Is there a way to implement a "listener" on a tdms file and read all incoming segments ? 

We are working on a platform to share data (live). Therefore we need a way to load the tdms files dynamically. I think Labview creates these tdms files and appends segments (?). It would be very helpfull to load the incoming segments.

**Comment by adamreeve** [comment]
Hi, no that's not currently possible with npTDMS and it wouldn't be straightforward to implement due to the way npTDMS works. The metadata of all segments is read in a first pass through the file before then reading the data.

I think it might be awkward to read TDMS files in this way as Labview writes a segment header with a placeholder value (-1) for the offset to the next segment, then streams data to the file, and once the segment is written and before a new segment is started, goes back and writes the actual next segment offset into the header. If you're trying to read data as it's written to the file you won't know when to expect the end of a segment. You can check for the "TDSm" tag which indicates the beginning of a segment but there's the possibility this is valid data.
