### ISSUE TITLE
Digital channels not loading properly

### ISSUE THREAD

**Issue by chaplinta** [adamreeve/npTDMS#211]
Hi,

I create some very simple TDMS files (attached) that should have digital pulses on 2 channels. When I open the TDMS file with Excel I can see there is data there, but when I try to load with npTDMS there is only data on line0 (the second channel in the bellow code example). I created the TDMS file with python nidaqmx, I guess there is a chance I did something weird to create a problem in the file, but as I said Excel can open it. I have attached an example data file.
[0022_2020-08-20_test_free.tdms.zip](https://github.com/adamreeve/npTDMS/files/5108597/0022_2020-08-20_test_free.tdms.zip)

I'd very much appreciate any suggestion of what might be going wrong here.

```
import nptdms
file_path = "0022_2020-08-20_test_free.tdms"

tdms_file = nptdms.TdmsFile.read(file_path)

group = tdms_file['_unnamedTask<0> - overhead']
channel = group['ExpDAQ/port0/line1']
channel_data = channel[:]
print(sum(channel_data)) # this should be non-zero, i.e. have pulses, but is zero
print(channel.properties)

group = tdms_file['_unnamedTask<0> - sci_frame']
channel = group['ExpDAQ/port0/line0']
channel_data = channel[:]
print(sum(channel_data)) # this should be non-zero, i.e. have pulses, it is correct
print(channel.properties)
```

**Comment by adamreeve** [comment]
Hi, thanks for the bug report and for providing an example.

It looks like the problem here is that the line1 channel has a "raw byte offset" of 1, but for digital channels this should actually be treated as a bit offset. The NI documentation on how DAQmx data is represented in TDMS is very limited and only describes "format changing scaler" data but not "digital line scaler" data, so it wasn't obvious that this property meant something different for digital data.

I've got a fix for this on the [issue_211 branch](https://github.com/adamreeve/npTDMS/tree/issue_211) but still need to fix the tests and tidy up before merging this and releasing the fix.

**Comment by chaplinta** [comment]
Thanks for quick reply, and this very useful package.
