### ISSUE TITLE
Zero channel data size but non-zero data length based on segment offset

### ISSUE THREAD

**Issue by chaitanya-ather** [adamreeve/npTDMS#76]
Creating a new issue based on comments here: https://github.com/adamreeve/npTDMS/issues/61#issuecomment-319014146

I am facing this error while trying to read a DAQmx tdms file. 
I am using v0.11.2. In tdms.py where the error is raised, total_data_size = 140 while data_size = 0.

I have attached the tdmsfo --debug output below.

[acquired_daqmxdatainfo.txt](https://github.com/adamreeve/npTDMS/files/1206949/acquired_daqmxdatainfo.txt)

**Comment by adamreeve** [comment]
@chaitanya-ather, apologies for the very long time taken to look into this. I think I may have fixed this issue in the latest commit to the master branch, so if you are still able to can you test whether this has fixed your problem? It looks like the way the chunk size was being set for DAQmx raw data was incorrect but had worked correctly for the test file by chance due to the way reading interleaved data worked.
