### ISSUE TITLE
Python int too large to convert to C long

### ISSUE THREAD

**Issue by jfdzar** [adamreeve/npTDMS#78]
Hi @adamreeve ,
I am having problems loading large TDMS files (>750MB).
A possible solution I have though about is reading only the channels I need (that's how actually LabVIEW does). My Idea was to make a condition on read_raw_data function which only load the channles I need
Something like "if obj.path.split('/')[2][1:-1] in selected_channels:" ( I have not taken into account the group because my channels have only unique identifiers)

I have forked your library and I have implemented this condition. But I cannot run it because the read function of types.py shows me this exception "Python int too large to convert to C long" when running timedelta(seconds=seconds)

Do you know what can it be?

If I run the library from the site-packages.nptdms it works correctly unless I execute step by step (I do it with eclipse) that it also throws me this exception. Do you know what it can be?

Have you though about implementing the read only of selected channels?

Thanks very much and thanks for the library is a great work!

**Comment by adamreeve** [comment]
I'm not sure why you're seeing that error, I'd guess there's a bug in your implementation that's causing the wrong data to be read at that point, because any date up to about the year 6000 should work with that method from my testing.

I have considered implementing lazy reading of channels so that the data is only read when needed, or only reading specific channels, but I don't use nptdms any more myself so am not implementing any new features.
