### ISSUE TITLE
Raw Data Index Length was Incorrect

### ISSUE THREAD

**Issue by jessykate** [adamreeve/npTDMS#86]
When using npTDMS writer all seems well, but when reading the files into matlab I am getting the error:

`Raw Data Index Length was Incorrect 16 stated vs. 20 observed, likely indicates bad code or file`
![image](https://user-images.githubusercontent.com/59882/33341998-631abab6-d435-11e7-9b66-382375fc853a.png)

We're using [this plugin](https://www.mathworks.com/matlabcentral/fileexchange/30023-tdms-reader) for matlab. Reading the TDMS file works in several other applications (Diadem, qtiplot). 

From reading the [TDMS file format docs](http://www.ni.com/white-paper/5696/en/), I understand that the first argument of raw data index represents the _length_ of the raw data index. In writer.py, I can [see](https://github.com/adamreeve/npTDMS/blob/master/nptdms/writer.py#L126) that the index header is being set explicitly to 16. When I edit the above-linked line to set the first value to 20 instead of 16 (since this is what was observed), the import into matlab works, and the file continues to work in other applications as well. 

But how is this working in other apps. if the value of 20 really does represent the length of the index? Is this is a bug with this library, or our matlab import function? Can you help explain what is happening here, if possible?

We are dealing with files that typically have about 3 groups with somewhere between 10 and 200 channels in them, and tend to be ~100Mb in size. 

Many thanks!

**Comment by adamreeve** [comment]
Hi

It looks like this is a bug in the npTDMS library. I think I probably assumed the length was excluding the size taken up by the length value itself, but the size should be 20 if it includes the length.

I imagine this didn't cause problems for other applications because the size will usually always be 20, unless there is string data being written, in which case the size will be 28.

I'll make a change to fix this and write the size as 20.
