### ISSUE TITLE
Number scaling error on import

### ISSUE THREAD

**Issue by mgarrett1955** [adamreeve/npTDMS#91]
Hello, Thank you for the package!!

Im having and issue reading in a tdms file. I am getting the error:
WARNING:nptdms.scaling:Unsupported scale type: PieceWisePolynomial

I am using Jupyter. I am getting data, that looks like raw data, if this error is encountered, does the return value default to raw?

**Comment by mgarrett1955** [comment]
I used the tdmsinfo command line program to read the header information, and can see that the scaling type is piecewise polynomial, which is most likely the extended floating point type not supported by this version. So Im assuming that the raw data got exported. In addition, is there a python function for dumping all of the properties, similar to the command line(I did not take a long time to search, the documentation is great by the way, I just haven't looked!! )Thank again!

**Comment by adamreeve** [comment]
Hi, yes in this case the raw unscaled data will be returned instead of the scaled data. There isn't a single function for dumping all properties, but you can use the `properties` attribute of a tdms object to access its properties as a dictionary. It might help to look at how tdmsinfo is implemented: https://github.com/adamreeve/npTDMS/blob/master/nptdms/tdmsinfo.py

**Comment by mgarrett1955** [comment]
Thank you!!
